version: "1.0"
info:
  model: int-scaffold
packages:
- name: MIUN_trial3Project
  gitServerName: MIUNSAG_GH
  gitUrl: https://github.com/miunsag/MIUN_trial3Project
  gitUsername: miunsag
  gitBranch: main
- name: WxAdvanced
  version: "1.0"
  gitServerName: MIUNSAG_GH
  gitUrl: https://github.com/miunsag
  gitUsername: miunsag
  gitBranch: main
services:
- serviceName: project.miun_trial3.integrations:Trial5
  packages:
  - name: MIUN_trial3Project
    version: "1.0"
  - name: webmethods-integrationserver-wxssh
    version: "1.0"
  - name: WxAdvanced
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: wx.advanced.flow:invoke
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: wx.advanced.env:getEnvPropsList
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: wx.advanced.is:describeRuntime
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: wx.advanced.env:getEnvProp
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: wx.advanced.env:getSysPropsList
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: wx.advanced.env:getSysProp
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: wx.advanced.sh:exec
  packages:
  - name: WxAdvanced
    version: "1.0"
- serviceName: project.miun_trial3.integrations:e6
  packages:
  - name: MIUN_trial3Project
    version: "1.0"
  - name: webmethods-integrationserver-wxssh
    version: "1.0"
  - name: WxAdvanced
    version: "1.0"
- serviceName: project.miun_trial3.integrations:i7
  packages:
  - name: MIUN_trial3Project
    version: "1.0"
  - name: WxAdvanced
    version: "1.0"
- serviceName: project.miun_trial3.integrations:DADA1ibmmi
  packages:
  - name: MIUN_trial3Project
    version: "1.0"
  - name: WxAdvanced
    version: "1.0"
